#!/usr/bin/env bash

PIPE=
SELECTED=0
CURRENT_DIR="$(pwd)"
CURRENT_DIR_CONTENT=()

escape()
{
	case "$1" in
		clear) printf "\e[2J";;
		save_term) printf "\e[?1049h";;
		restore_term) printf "\e[?1049l";;
		save_cursor) printf "\e7";;
		restore_cursor) printf "\e8";;
		move_cursor_up) printf "\e[%sA" "${2:-1}";;
		move_cursor_down) printf "\e[%sB" "${2:-1}";;
		set_cursor) printf "\e[%s;%sH" "${2:-1}" "${3:-1}";; # row, col
		hide_cursor) printf "\e[?25l";;
		show_cursor) printf "\e[?25h";;
		reset) printf "\e[0m";;
		erase_line_to_cursor) printf "\e[1K";;
		invert_color) printf "\e[7m";;
		reset_color) printf "\e[27m";;
	esac
}

cleanup()
{
	escape restore_term
	escape show_cursor
	escape reset
	rm $PIPE
	kill %%
}

get_term_size()
{
	read -r LINES COLUMNS < <(stty size)
}

render_bottom()
{
	escape set_cursor $(($LINES))
	local selected="$CURRENT_DIR/${CURRENT_DIR_CONTENT[$SELECTED]}"
	printf "%s" "$(stat -c "%A %G " $selected)"
	printf "%s" "$(format_bytes "$(stat -c "%s" $selected)") "
	printf "%s" "$(date -d "$(stat -c "%z" $selected)" +'%Y-%m-%d %H:%M')"
}

get_current_dir_content() 
{
	CURRENT_DIR_CONTENT=($(ls -a $CURRENT_DIR))
}

clear_file_list()
{
	for (( i=0; i < ${#CURRENT_DIR_CONTENT[@]}; i++ )); do
		escape set_cursor $(($i+2)) $(($COLUMNS/2))
		escape erase_line_to_cursor
	done
}

render_file_list_entry()
{
	local id=$1
	if (( $id	>= 0 && $id < ${#CURRENT_DIR_CONTENT[@]} )); then
		escape set_cursor $(($id+2)) $(($COLUMNS/2))
		escape erase_line_to_cursor
		escape set_cursor $(($id+2))
		if (( $id == $SELECTED )); then
			escape invert_color
		fi
		local element=${CURRENT_DIR_CONTENT[$id]}
		printf "%-$(($COLUMNS/2))s" "$element"
		escape reset_color
	fi
}

render_entire_file_list()
{
	local iter=0
	for element in ${CURRENT_DIR_CONTENT[@]}; do
		render_file_list_entry $iter
		((iter+=1))
	done
}

render_top_bar()
{
	escape set_cursor
	local selected=${CURRENT_DIR}
	printf "%s" "$(whoami)@$(uname -n) "
	printf "%s" "$selected"
}


file_list_move_up()
{
	((SELECTED-=1))
	if (( $SELECTED < 0 )); then
		SELECTED=0
	fi
	render_file_list_entry $SELECTED
	render_file_list_entry $(($SELECTED+1))
	render_bottom
}

file_list_move_down()
{
	((SELECTED+=1))
	if (( $SELECTED >= ${#CURRENT_DIR_CONTENT[@]} )); then
		SELECTED=$((${#CURRENT_DIR_CONTENT[@]} - 1))
	fi
	render_file_list_entry $SELECTED
	render_file_list_entry $(($SELECTED-1))
	render_bottom
}

file_list_open()
{
	if [[ -d "${CURRENT_DIR_CONTENT[$SELECTED]}" ]]; then
		cd "$CURRENT_DIR/${CURRENT_DIR_CONTENT[$SELECTED]}" &>/dev/null
		CURRENT_DIR="$(pwd)"
		clear_file_list
		get_current_dir_content
		render_entire_file_list
		render_top_bar
	fi
}

format_bytes()
{
	local bytes=$1
	local units=("B" "KiB" "MiB" "GiB" "TiB")
	local i=0

	while (( bytes >= 1024 && i < ${#units[@]} - 1 )); do
		bytes=$(( bytes / 1024 ))
		((i++))
	done

	echo "${bytes}${units[$i]}"
}

redraw()
{
	escape clear
	get_current_dir_content
	render_entire_file_list
	render_top_bar
	render_bottom
}

handle_keyboard_input()
{
	while true; do
		# Handling Input
		local input=""
		read -rsn1  input 2>/dev/null || return
		# Read 2 chars if first char is an escape charcter (to handle arrow keys)
		if [[ $input == $'\u1b' ]]; then
			read -rsn2 input 2>/dev/null || return
		fi

		local output=''
		case "$input" in
			'[A' | k) output='cursor_up';;
			'[B' | j) output='cursor_down';;
			'') output='enter';;
			q) output='quit';;
		esac

		if [[ -n $output ]]; then
			echo $output >&$fd
		fi
	done
}

main()
{
	trap cleanup exit

	escape save_term
	escape hide_cursor
	escape clear

	# Populates the COLUMNS and LINES vars
	shopt -s checkwinsize
	# Ensures the vars referenced above are set ¯\_(ツ)_/¯
	(:)

	trap redraw SIGWINCH
	redraw

	PIPE=/tmp/dora_keyboard_input_$$
	mkfifo $PIPE
	exec {fd}<>$PIPE

	exec {fd2}</dev/tty
	handle_keyboard_input <&$fd2 &

	# Handle events
	while true; do
		read -r -t 0.05 input <&$fd

		case "$input" in
			cursor_up) file_list_move_up;;
			cursor_down) file_list_move_down;;
			enter) file_list_open;;
			quit) exit;;
		esac
	done
}

main "$@"
