#!/usr/bin/env bash

source include/help
source include/grep
source include/navigation
source include/command
source include/search

# type, mod, name, size
init_sorting "type"
PIPE=

# normal, command, search
MODE="normal" 
CURRENT_INPUT=""
CURRENT_MESSAGE=""

# preview, grep
RIGHT_PANEL_MODE="preview"

enter_grep_mode()
{
	log_debug "Entering GREP right mode"
	RIGHT_PANEL_MODE="grep"
	update_grep_result "$1"
	render_right_panel
}

enter_preview_mode()
{
	log_debug "Entering PREVIEW right mode"
	RIGHT_PANEL_MODE="preview"
	update_selected_content
	render_right_panel
}

execute_input()
{
	case "$MODE" in
		command) execute_command;;
		search) reset_mode;;
	esac
}

set_input_message()
{
	CURRENT_MESSAGE="$1"
	log_debug "Setting message: \"$CURRENT_MESSAGE\""
	render_input
}

add_character()
{
	CURRENT_INPUT+="$1"
	render_input

	case  "$MODE" in
		search) 
			SEARCH_QUERY="$CURRENT_INPUT"
			update_search;;
	esac
}

remove_character()
{
	if [ -z "$CURRENT_INPUT" ]; then
		reset_mode
		return
	fi
	CURRENT_INPUT="${CURRENT_INPUT:0:-1}"
	render_input

	case  "$MODE" in
		search) 
			SEARCH_QUERY="$CURRENT_INPUT"
			update_search;;
	esac
}

reset_mode() {
	log_debug "Entering NORMAL mode"
	MODE="normal"
	render_input
	escape cursor_disable_blinking
	escape hide_cursor
}

fatal()
{
	log_error "$*"
	exit 1
}

cleanup()
{
	escape restore_term
	escape show_cursor
	escape reset
	tput rmcup
	tput smam
	rm $PIPE
	kill %% 2>/dev/null
}

handle_keyboard_input()
{
	while true; do
		# Handling Input
		local input=""
		IFS= read -rsn1  input 2>/dev/null || return
		# Read 2 chars if first char is an escape charcter (to handle arrow keys)
		if [[ $input == $'\x1b' ]]; then
			local rest=""
			while IFS= read -rsn1 -t 0.01 char 2>/dev/null; do
				rest+="$char"
			done
			if [[ -n "$rest" ]]; then
				input="$rest"
			else
				input="ESCAPE"
			fi
		elif [[ $input = $'\x08' || $input = $'\x7f' ]]; then
			input="BACKSPACE"
		elif [[ $input = " " ]]; then
			input=" "
		fi

		if [[ -n "$input" ]]; then
			echo "$input" >&$fd
		else
			echo "RETURN" >&$fd
		fi
	done
}

exit_input()
{
	CURRENT_MESSAGE=""
	escape hide_cursor
	case "$MODE" in
		search) 
			reset_search
			directory_change
			;;
	esac
	reset_mode
}

main()
{
	# Init logging
	mkdir -p "$LOG_DIR" || fatal "Failed to init logging directory"

	# Parse command line options
	ARGS=()
	while [[ $# -gt 0 ]]; do
		case $1 in
			-h|--help) 
				show_help
				exit 0 ;;
			-l|--logs)
				show_logs
				exit 0 ;;
			-*)
				echo "Unknown option: $1"
				fatal "Unknown option: $1"
				;;
			*)
				ARGS+=("$1")
				shift
				;;
		esac
	done

	tput smcup
	tput rmam
	# Prepare terminal for rendering
	trap cleanup exit

	escape save_term
	escape hide_cursor
	escape clear
	redraw

	# Try to cd into directory if provided with one
	set -- "${ARGS[@]}"
	if [[ -n $1 ]]; then
		file_list_open "$1"
	fi

	# Setup named pipes for communication
	PIPE=/tmp/dora_keyboard_input_$$
	mkfifo $PIPE
	exec {fd}<>$PIPE
	exec 2>"$LOG_FILE"

	exec {fd2}</dev/tty
	handle_keyboard_input <&$fd2 &

	# Handle events
	while true; do
		IFS="" read -r -t 0.1 input <&$fd

		local old_rows=$ROWS
		local old_cols=$COLS
		get_term_size

		if [[ "$old_rows" -ne "$ROWS" || "$old_cols" -ne "$COLS" ]]; then
			redraw
		fi

		if [[ -z "$input" ]]; then
			continue
		fi

		case "$MODE" in
			normal)
				case "$input" in
					'[A' | k) file_list_move_selection -1;;
					'[B' | j) file_list_move_selection 1;;
					'[C' | l) file_list_open;;
					'[D' | h | -) file_list_open ..;;
					'RETURN') file_list_open;;
					':') enter_command_mode;;
					'/') enter_search_mode;;
					q) exit;;
				esac;;
			*)
				case "$input" in
					'ESCAPE') exit_input;;
					'BACKSPACE') remove_character;;
					'RETURN') execute_input;;
					*) add_character "$input";;
				esac;;
		esac
	done
}

main "$@"
