#!/usr/bin/env bash

source include/logging
source include/help

PIPE=
SELECTED=0
ROWS=
COLS=
FILE_LIST_OFFSET=0
CURRENT_DIR="$(pwd)/"
CURRENT_DIR_CONTENT=()

# type, mod, name, size
SORTING="name"

# normal, command
MODE="normal"

CURRENT_COMMAND=""

fatal()
{
	log_error "$*"
	exit 1
}

escape()
{
	case "$1" in
		clear) printf "\e[2J";;
		save_term) printf "\e[?1049h";;
		restore_term) printf "\e[?1049l";;
		save_cursor) printf "\e7";;
		restore_cursor) printf "\e8";;
		move_cursor_up) printf "\e[%sA" "${2:-1}";;
		move_cursor_down) printf "\e[%sB" "${2:-1}";;
		set_cursor) printf "\e[%s;%sH" "${2:-1}" "${3:-1}";; # row, col
		hide_cursor) printf "\e[?25l";;
		show_cursor) printf "\e[?25h";;
		reset) printf "\e[0m";;
		erase_line_to_cursor) printf "\e[1K";;
		invert_color) printf "\e[7m";;
		reinvert_color) printf "\e[27m";;
		black_color) printf "\e[30m";;
		red_color) printf "\e[31m";;
		green_color) printf "\e[32m";;
		yellow_color) printf "\e[33m";;
		blue_color) printf "\e[34m";;
		magenta_color) printf "\e[35m";;
		cyan_color) printf "\e[36m";;
		white_color) printf "\e[37m";;
		default_color) printf "\e[39m";;
		black_bg_color) printf "\e[40m";;
		red_bg_color) printf "\e[41m";;
		green_bg_color) printf "\e[42m";;
		yellow_bg_color) printf "\e[43m";;
		blue_bg_color) printf "\e[44m";;
		magenta_bg_color) printf "\e[45m";;
		cyan_bg_color) printf "\e[46m";;
		white_bg_color) printf "\e[47m";;
		default_bg_color) printf "\e[49m";;
		dim) printf "\e[2m";;
		undim) printf "\e[22m";;
	esac
}

cleanup()
{
	escape restore_term
	escape show_cursor
	escape reset
	rm $PIPE
	kill %%
}

get_term_size()
{
	ROWS=$(tput lines)
	COLS=$(tput cols)
}

justify_to_term_width()
{
	local left=$1
	local right=$2

	len=$((COLS - ${#left} - ${#right}))
		spaces=$(printf "%${len}s" "")
		printf "%s" "$left$spaces$right"
	}

render_bottom()
{
	local left right spaces selected

	escape set_cursor "$((ROWS - 1))" 0
	selected=${CURRENT_DIR_CONTENT[SELECTED]}

	left="$(stat -c "%A %G " "$selected")"
	left="$left$(format_bytes "$(stat -c "%s" "$selected")") "
	left="$left$(date -d "$(stat -c "%z" "$selected")" +'%Y-%m-%d %H:%M')"

	right="$ROWS x $COLS"

	justify_to_term_width "$left" "$right"
}


render_top()
{
	escape set_cursor
	local selected="$(escape blue_color)$CURRENT_DIR$(escape white_color)${CURRENT_DIR_CONTENT[SELECTED]}"
	justify_to_term_width "$(escape green_color)$(whoami)@$(uname -n)$(escape white_color) $selected"
}

get_current_dir_content() 
{
	CURRENT_DIR_CONTENT=($(ls -A "$CURRENT_DIR"))
	case "$SORTING" in
		type) CURRENT_DIR_CONTENT=($(ls -A --group-directories-first));;
		size) CURRENT_DIR_CONTENT=($(ls -AS "$CURRENT_DIR"));;
		name) CURRENT_DIR_CONTENT=($(ls -A "$CURRENT_DIR"));;
		mod) CURRENT_DIR_CONTENT=($(ls -At "$CURRENT_DIR"));;
	esac
}

clear_file_list()
{
	for (( i=2; i < $((ROWS-1)); i++ )); do
		escape set_cursor $i $((COLS/2))
		escape erase_line_to_cursor
	done
}

is_file_visible()
{
	local pos=$(($1-FILE_LIST_OFFSET+2))
	if (( pos	>= 2 && pos < $((ROWS-1)) )); then
		return 1;
	fi
	return 0;
}

render_file_list_entry()
{
	local id=$1
	local pos=$((id-FILE_LIST_OFFSET+2))
	is_file_visible "$id"
	local visible=$?
	if [[ "$visible" = "1" ]]; then
		escape set_cursor $pos
		if (( id == SELECTED )); then
			escape invert_color
		fi
		local element=${CURRENT_DIR_CONTENT[$id]}
		local global_element="$CURRENT_DIR$element"
		if [[	-d "$global_element" ]]; then
			escape blue_color
		elif [[	-L "$global_element" ]]; then
			escape cyan_color
		elif [[	-f "$global_element" ]]; then
			escape default_color
			if [[	-x "$global_element" ]]; then
				escape green_color
			fi
		elif [[	-b "$global_element" ]]; then
			escape yellow_color
		elif [[	-c "$global_element" ]]; then
			escape magenta_color
		else
			escape dim
			escape white_color
		fi
		printf "%-$((COLS/2))s" " $element"
		escape reset
	fi
}

render_entire_file_list()
{
	local iter=0
	for element in "${CURRENT_DIR_CONTENT[@]}"; do
		render_file_list_entry $iter
		((iter+=1))
	done
}

set_sorting()
{
	SORTING=$1
	get_current_dir_content
	render_entire_file_list
}

file_list_move_up()
{
	((SELECTED-=1))
	if (( SELECTED < 0 )); then
		SELECTED=0
	fi
	is_file_visible $SELECTED
	local visible=$?
	if [[ "$visible" ==	"0" ]]; then
		FILE_LIST_OFFSET=$(( FILE_LIST_OFFSET - 1	))
		render_entire_file_list
	else
		render_file_list_entry $SELECTED
		render_file_list_entry $((SELECTED+1))
	fi
	render_bottom
	render_top
}

file_list_move_down()
{
	((SELECTED+=1))
	if (( SELECTED >= ${#CURRENT_DIR_CONTENT[@]} )); then
		SELECTED=$((${#CURRENT_DIR_CONTENT[@]} - 1))
	fi
	is_file_visible $SELECTED
	local visible=$?
	if [[ "$visible" ==	"0" ]]; then
		FILE_LIST_OFFSET=$(( FILE_LIST_OFFSET + 1	))
		render_entire_file_list
	else
		render_file_list_entry $SELECTED
		render_file_list_entry $((SELECTED-1))
	fi
	render_bottom
	render_top
}

file_list_open()
{
	local dest="${1:-${CURRENT_DIR_CONTENT[$SELECTED]}}"
	log_debug "Opening $dest"
	if [[ -d "$dest" ]]; then
		cd "$CURRENT_DIR$dest" &>/dev/null || fatal "Failed to open $CURRENT_DIR$dest"
		CURRENT_DIR="$(pwd)/"
		if [[ "$CURRENT_DIR" == "//" ]]; then
			CURRENT_DIR="/"
		fi
		SELECTED=0
		FILE_LIST_OFFSET=0
		clear_file_list
		get_current_dir_content
		render_entire_file_list
		render_top
		render_bottom
	fi
}

format_bytes()
{
	local bytes=$1
	local units=("B" "KiB" "MiB" "GiB" "TiB")
	local i=0

	while (( bytes >= 1024 && i < ${#units[@]} - 1 )); do
		bytes=$(( bytes / 1024 ))
		((i++))
	done

	echo "${bytes}${units[$i]}"
}

redraw()
{
	get_term_size

	escape clear
	get_current_dir_content
	SELECTED=0
	render_entire_file_list
	render_top
	render_bottom
	render_command
}

execute_command()
{
	local tokens=()
	IFS=" " read -a tokens <<< "$1"
	case "${tokens[0]}" in
		*) log_info "${#tokens[@]}"
	esac
}

render_command()
{
	escape set_cursor $ROWS
	printf ":%s" "$CURRENT_COMMAND"
}

start_command()
{
	log_debug "COMMAND"
	MODE="command"
	CURRENT_COMMAND=""
	render_command
}

reset_mode()
{
	log_debug "NORMAL"
	MODE="normal"
}

handle_keyboard_input()
{
	while true; do
		# Handling Input
		local input=""
		read -rsn1  input 2>/dev/null || return
		# Read 2 chars if first char is an escape charcter (to handle arrow keys)
		if [[ $input == $'\u1b' ]]; then
			local rest=""
			while IFS= read -rsn1 -t 0.01 char 2>/dev/null; do
        rest+="$char"
      done
			if [[ -n "$rest" ]]; then
				input="$rest"
			else
				input="ESC"
			fi
		fi

		if [[ -n "$input" ]]; then
			echo $input >&$fd
		else
			# SpaceEnter
			echo "BLANK" >&$fd
		fi
	done
}

main()
{
	# Init logging
	mkdir -p "$LOG_DIR" || fatal "Failed to init logging directory"

	# Parse command line options
	while [[ $# -gt 0 ]]; do
		case $1 in
			-h|--help) 
				show_help
				exit 0 ;;
			-l|--logs)
				show_logs
				exit 0 ;;
			-*)
				echo "Unknown option: $1"
				fatal "Unknown option: $1"
				;;
			*)
				shift
				;;
		esac
	done

	# Prepare terminal for rendering
	trap cleanup exit

	escape save_term
	escape hide_cursor
	escape clear
	redraw

	# Setup named pipes for communication
	PIPE=/tmp/dora_keyboard_input_$$
	mkfifo $PIPE
	exec {fd}<>$PIPE

	exec {fd2}</dev/tty
	handle_keyboard_input <&$fd2 &

	# Handle events
	while true; do
		read -r -t 0.1 input <&$fd

		local old_rows=$ROWS
		local old_cols=$COLS
		get_term_size
		if [[ "$old_rows" -ne "$ROWS" || "$old_cols" -ne "$COLS" ]]; then
			redraw
		fi

		if [[ -z "$input" ]]; then
			continue
		fi

		log_debug "$input"

		case "$MODE" in
			normal)
				case "$input" in
					'[A' | k) file_list_move_up;;
					'[B' | j) file_list_move_down;;
					'[C' | l) file_list_open;;
					'[D' | h | -) file_list_open ..;;
					'BLANK') file_list_open;;
					':') start_command;;
					q) exit;;
				esac;;
			command)
				case "$input" in
					'ESC') reset_mode;;
					*) 
						CURRENT_COMMAND+="$input"
						render_command
				esac;;
		esac
	done
}

main "$@"
