#!/usr/bin/env bash

source include/rendering

CURRENT_COMMAND=""
CURRENT_MESSAGE=""
COMMAND_HISTORY=()
COMMAND_HISTORY_POSITION="1"
COMMAND_DRAFT=""

set_command_line_message()
{
	CURRENT_MESSAGE="$1"
	log_debug "Setting message: \"$CURRENT_MESSAGE\""
	render_command
}

enter_command_mode()
{
	log_debug "Entering COMMAND mode"
	CURRENT_INPUT="$CURRENT_COMMAND"
	COMMAND_HISTORY_POSITION="${#COMMAND_HISTORY[@]}"
	MODE="command"
	render_input
}

command_sort() 
{
	local sorting=$1

	if [[ -z "$sorting" ]]; then
		set_input_message "$(escape red_color)You must supply a sorting scheme$(escape default_color)"
		return 1
	fi

	case "$sorting" in
		type | size | name | mod) 
			set_input_message "Sorting by $sorting"
			set_sorting "$sorting";;
		*) set_input_message "$(escape red_color)$sorting is not a supported sorting scheme$(escape default_color)";;
	esac
}

command_hidden()
{
	local arg=$1

	# If ran with no arguments toggle
	if [ -z "$arg" ]; then
		case "$SHOW_HIDDEN" in
			'1') 
				set_input_message "Disabled showing .hidden files"
				set_hidden 0;;
			'0')
				set_input_message "Enabled showing .hidden files"
				set_hidden 1;;
		esac
		return 0
	fi

	case "$arg" in
		true|1|yes)
			set_input_message "Enabled showing .hidden files"
			set_hidden 1
			;;
		false|0|no)
			set_input_message "Disabled showing .hidden files"
			set_hidden 0
			;;
*) set_input_message "$(escape red_color)$1 is not a supported boolean alias$(escape default_color)";;
	esac
	reset_mode
}

move_command_history()
{
	local history_size="${#COMMAND_HISTORY[@]}"
	local dest="$(($COMMAND_HISTORY_POSITION + $1))"
	if [[ "$dest" -ge "$history_size" ]]; then
		CURRENT_INPUT="$COMMAND_DRAFT"
		CURRENT_COMMAND="$CURRENT_INPUT"
		dest="$history_size"
	elif [[ "$dest" -ge "0" ]]; then
		CURRENT_INPUT="${COMMAND_HISTORY[$dest]}"
		CURRENT_COMMAND="$CURRENT_INPUT"
	else
		dest="0"
	fi
	COMMAND_HISTORY_POSITION="$dest"
	render_input
}

update_command_draft()
{
	if [[ "$dest" -ge "$history_size" ]]; then
		COMMAND_DRAFT="$CURRENT_COMMAND"
	fi
}

mark_file()
{
	# Tries to mark $1 but if empty use the currently selected file
	local mark=${1:-"${CURRENT_DIR_CONTENT[$SELECTED]}"}

	if ! [ -e "$CURRENT_DIR$mark" ]; then
		set_input_message "$(escape red_color)$mark doesn't exist$(escape default_color)"
		return 1
	fi

	MARKED=$mark
	MARKED_DIR="$CURRENT_DIR"
	log_debug "Marked $MARKED_DIR$MARKED"
	set_input_message "Marked $MARKED"
	render_top
}

edit_marked()
{
	if [[ -z "$MARKED" ]]; then
		set_input_message "$(escape red_color)No file has been marked (:mark)$(escape default_color)"
		return 1
	fi

	local op=$1
	case $op in
		move)
			local dest=$2
			mv "$MARKED_DIR$MARKED" "$dest"
			MARKED_DIR="$dest"
			log_debug "Moved $MARKED_DIR$MARKED to $dest"
			set_input_message "Moved $MARKED to $dest"
			directory_change
			;;
		copy)
			local dest=$2
			local flags=()
			if [[ -d "$MARKED_DIR$MARKED" ]]; then
				flags=(-r)
			fi
			cp "${flags[@]}" "$MARKED_DIR$MARKED" "$dest"
			log_debug "Copied $MARKED_DIR$MARKED to $dest"
			set_input_message "Copied $MARKED to $dest"
			directory_change
			;;
		delete)
			rm -rf "$MARKED_DIR$MARKED"
			log_debug "Deleted $MARKED_DIR$MARKED"
			set_input_message "Deleted $MARKED"
			MARKED=""

			render_top
			if [ "$MARKED_DIR" = "$CURRENT_DIR" ]; then
				redraw
			fi
			;;
	esac
}

start_command()
{
	enter_command_mode
	CURRENT_INPUT="$1"
	render_input
}

create_command()
{
	if [ $# = 0 ]; then
		set_input_message "$(escape red_color)You must name at least one file$(escape default_color)"
		return 1
	fi

	for file in "$@"; do
		create_file_dir "$file"
	done

	if [ $# = 1 ]; then
		set_input_message "Created $1"
	else
		set_input_message "Created $# files"
	fi

	directory_change
}

create_file_dir()
{
	local path="$1"
	if [[ "$path" == */ ]]; then
		mkdir -p "$path"
	else
		mkdir -p "$(dirname "$path")"
		touch "$path"
	fi

	log_debug "Created $path"
}

execute_command()
{
	local tokens=()
	read -ra tokens <<< "$CURRENT_INPUT" 2>/dev/null
	log_debug "Executing command \"${tokens[0]}\", full prompt: \"$CURRENT_INPUT\""
	case "${tokens[0]}" in
		sort) command_sort "${tokens[1]}";;
		mark) mark_file "${tokens[1]}";;
		cp|copy) edit_marked copy "$CURRENT_DIR";;
		mv|move) edit_marked move "$CURRENT_DIR";;
		rm|remove|delete) edit_marked delete;;
		create|touch) create_command "${tokens[@]:1}";;
		hidden) command_hidden "${tokens[1]}";;
		q|quit) exit 0;;
		*) set_input_message "$(escape red_color)Command ${tokens[0]} not found$(escape default_color)";;
	esac
	COMMAND_HISTORY+=("$CURRENT_COMMAND")
	CURRENT_COMMAND=""
	reset_mode
}
