#!/usr/bin/env bash

GREP_RESULT=""
GREP_PATTERN=""

update_grep_result()
{
	local selected="$CURRENT_DIR${CURRENT_DIR_CONTENT[$SELECTED]}"
	local content=

	if [ -d "$selected" ]; then
		content="$(grep -PIr -m 200 "$GREP_PATTERN" "$selected" 2>/dev/null | tr '\0' '\n' 2>/dev/null)"
	elif [ -f "$selected" ]; then
		content="$(grep -PI -m 200 "$GREP_PATTERN" "$selected" 2>/dev/null | tr '\0' '\n' 2>/dev/null)"
	fi

	GREP_RESULT="$content"
	grep_change
}

enter_grep_mode()
{
	log_debug "Entering GREP mode"
	CURRENT_INPUT="$GREP_PATTERN"
	RIGHT_PANEL_MODE="grep"
	MODE="grep"
	update_grep_result
	render_right_panel
	render_input
}

reset_grep() 
{
	GREP_PATTERN=""
	enter_preview_mode
}
