#!/usr/bin/env bash

source include/rendering

GREP_RESULT=""
GREP_PATTERN=""

update_grep_result()
{
	if [[ -n "$1" ]]; then
		GREP_PATTERN="$1"
		log_debug "New grep pattern: $GREP_PATTERN"
	fi
	local selected="$CURRENT_DIR${CURRENT_DIR_CONTENT[$SELECTED]}"
	local content=

	if [ -d "$selected" ]; then
		content="$(grep -PIr -m 200 "$GREP_PATTERN" $selected | tr '\0' '\n' 2>/dev/null)"
	elif [ -f "$selected" ]; then
		content="$(grep -PI -m 200 "$GREP_PATTERN" $selected | tr '\0' '\n' 2>/dev/null)"
	fi

	GREP_RESULT="$content"
}
