#!/usr/bin/env bash

source include/rendering

CURRENT_DIR="$(pwd)/"
SELECTED=0
FILE_LIST_OFFSET=0
CURRENT_DIR_CONTENT=()
SELECTED_CONTENT=
LS_SORTING_FLAGS=()

LS_HIDDEN_FLAGS=(-A)
SHOW_HIDDEN=1

# Rerenders components which depend on the currently active file
# (except the dir content as its handled separately)
file_change()
{
	render_top
	render_bottom
	update_right_panel_data
	render_right_panel
}

# Rerenders everything without fetching new terminal dimensions 
# and updating variables
directory_change()
{
	clear_file_list
	get_current_dir_content
	render_entire_file_list
	render_top
	render_bottom
	update_right_panel_data
	render_right_panel
}

# Works like directory_change() but doesn't update the current
# directory content
search_change()
{
	SELECTED=0
	escape hide_cursor
	clear_file_list
	render_entire_file_list
	render_top
	render_bottom
	update_selected_content
	if [ "$MODE" = "search" ]; then
		render_input
	fi
}

set_sorting()
{
	init_sorting "$@"
	directory_change
	update_search
}

init_sorting()
{
	SORTING=$1
	log_debug "Sorting mode set to: \"$SORTING\"";
	LS_SORTING_FLAGS=()
	case "$SORTING" in
		type) LS_SORTING_FLAGS=(--group-directories-first);;
		size) LS_SORTING_FLAGS=(-S);;
		name) LS_SORTING_FLAGS=();;
		mod) LS_SORTING_FLAGS=(-t);;
	esac
}

set_hidden()
{
	SHOW_HIDDEN=$1
	LS_HIDDEN_FLAGS=()
	if [ "$SHOW_HIDDEN" = "1" ]; then
		LS_HIDDEN_FLAGS=(-A)
	fi
	redraw
	sync_search_files
	update_search
}

get_current_dir_content() 
{
	# Load the output of ls into the CURRENT_DIR_CONTENT array
	mapfile -t CURRENT_DIR_CONTENT < <(ls "${LS_HIDDEN_FLAGS[@]}" "${LS_SORTING_FLAGS[@]}" "$CURRENT_DIR")
}

update_selected_content()
{
	local dir_size=${#CURRENT_DIR_CONTENT[@]}
	
	if [[ "$dir_size" = "0" ]]; then
		SELECTED_CONTENT=
		render_selected_content
		return 1
	fi

	local height=$((ROWS - 3))
	local content=
	local selected="$CURRENT_DIR${CURRENT_DIR_CONTENT[$SELECTED]}"

	if [ -d "$selected" ]; then
		local files
		files="$(ls "${LS_HIDDEN_FLAGS[@]}" "${LS_SORTING_FLAGS[@]}" "$selected")"
		content=$(parse_file_list "$(head -"$height" <<< "$files")" "$selected")
	# Don't try to render binary files
	elif file --mime-encoding "$selected" | grep -q binary; then
		content="Can't preview binary file!"
	# tr to avoid null bytes which apparently mess up strings and most importantly send a random warning
	elif [ -f "$selected" ]; then
		content="$(head -"$height" "$selected" | tr '\0' '\n')"
	fi

	SELECTED_CONTENT=$content
}

update_right_panel_data()
{
	case "$RIGHT_PANEL_MODE" in
		preview) update_selected_content;;
		grep) update_grep_result;;
	esac
}

parse_file_list()
{
	local files=$1
	local dir=$2
	while IFS= read -r line; do
		get_filetype_color "$dir/$line"
		printf "%b\n" "$line"
		escape reset
		((i++))
	done <<< "$files"
}

is_file_visible()
{
	# +2 = +1 to account for the top bar, +1 because lines are 1 indexed
	local pos=$(($1-FILE_LIST_OFFSET+2))
	if (( pos > 1 && pos < $((ROWS - 2)) )); then
		return 1;
	fi
	return 0;
}

file_list_move_selection()
{
	local dir_size=${#CURRENT_DIR_CONTENT[@]}
	
	if [[ "$dir_size" = "0" ]]; then
		return 1
	fi

	local jump_size=${1:-1}
	local prev="$SELECTED"
	((SELECTED+=jump_size))

	if (( SELECTED >= dir_size )); then
		SELECTED=$((dir_size - 1))
		jump_size=$((SELECTED - prev))
	fi
	if (( SELECTED < 0 )); then
		SELECTED=0
		jump_size=$((SELECTED - prev))
	fi

	# Don't rerender components if the selected file didn't change
	if [[ "$jump_size" = "0" ]]; then
		return 0
	fi

	if is_file_visible $SELECTED; then
		FILE_LIST_OFFSET=$((FILE_LIST_OFFSET + jump_size))
		render_entire_file_list
	else
		render_file_list_entry $SELECTED
		render_file_list_entry $prev
	fi

	file_change
}

file_list_open()
{
	local dest="${1:-$CURRENT_DIR${CURRENT_DIR_CONTENT[$SELECTED]}}"
	reset_search

	if [[ -d "$dest" ]]; then
		cd "$dest" &>/dev/null && log_debug "Going to $dest" || \
			{ 
				log_debug "Going to $dest failed" 
				set_command_line_message "$(escape red_color)Failed to open $dest$(escape default_color)"
			}
		CURRENT_DIR="$(pwd)/"

		if [[ "$CURRENT_DIR" == "//" ]]; then
			CURRENT_DIR="/"
		fi

		SELECTED=0
		FILE_LIST_OFFSET=0
		directory_change
	else
		# TODO: open file with preferred editor
		true
	fi
}
