#!/usr/bin/env bash

source include/rendering

CURRENT_DIR="$(pwd)/"
SELECTED=0
FILE_LIST_OFFSET=0
CURRENT_DIR_CONTENT=()
SELECTED_CONTENT=

# type, mod, name, size
SORTING="type"

set_sorting()
{
	SORTING=$1
	get_current_dir_content
	render_entire_file_list
	update_selected_content
}

get_current_dir_content() 
{
	CURRENT_DIR_CONTENT=($(ls -A "$CURRENT_DIR"))
	case "$SORTING" in
		type) CURRENT_DIR_CONTENT=($(ls -A --group-directories-first));;
		size) CURRENT_DIR_CONTENT=($(ls -AS "$CURRENT_DIR"));;
		name) CURRENT_DIR_CONTENT=($(ls -A "$CURRENT_DIR"));;
		mod) CURRENT_DIR_CONTENT=($(ls -At "$CURRENT_DIR"));;
	esac
}

update_selected_content()
{
	local height=$((ROWS - 3))
	local content=
	local selected="$CURRENT_DIR${CURRENT_DIR_CONTENT[$SELECTED]}"

	# tr to avoid null bytes which apparently mess up strings and most importantly send a random warning
	if [[ -f $selected ]]; then
		content="$(head -"$height" "$selected" | tr '\0' '\n')"
	fi

	if [[ -d selected ]]; then
		true
	fi

	SELECTED_CONTENT=$content
	render_selected_content
}

is_file_visible()
{
	local pos=$(($1-FILE_LIST_OFFSET+2))
	if (( pos	>= 2 && pos < $((ROWS-1)) )); then
		return 1;
	fi
	return 0;
}

file_list_move_selection()
{
	local jump_size=${1:-1}
	local prev="$SELECTED"
	((SELECTED+=jump_size))

	if (( SELECTED >= ${#CURRENT_DIR_CONTENT[@]} )); then
		SELECTED=$((${#CURRENT_DIR_CONTENT[@]} - 1))
	fi
	if (( SELECTED < 0 )); then
		SELECTED=0
	fi

	is_file_visible $SELECTED
	local visible=$?
	if [[ "$visible" ==	"0" ]]; then
		FILE_LIST_OFFSET=$((FILE_LIST_OFFSET + jump_size))
		render_entire_file_list
	else
		render_file_list_entry $SELECTED
		render_file_list_entry $prev
	fi
	render_bottom
	render_top
	update_selected_content
}

file_list_open()
{
	local dest="${1:-$CURRENT_DIR${CURRENT_DIR_CONTENT[$SELECTED]}}"
	log_debug "Opening $dest"

	if [[ -d "$dest" ]]; then
		cd "$dest" &>/dev/null || fatal "Failed to open $dest"
		CURRENT_DIR="$(pwd)/"

		if [[ "$CURRENT_DIR" == "//" ]]; then
			CURRENT_DIR="/"
		fi

		SELECTED=0
		FILE_LIST_OFFSET=0
		clear_file_list
		get_current_dir_content
		render_entire_file_list
		render_top
		render_bottom
		update_selected_content
	else
		# TODO: open file with preferred editor
		true
	fi
}
