#!/usr/bin/env bash

source include/logging

ROWS=
COLS=

get_term_size()
{
	ROWS=$(tput lines)
	COLS=$(tput cols)
}

format_bytes()
{
	local bytes=$1
	local units=("B" "KiB" "MiB" "GiB" "TiB")
	local i=0

	while (( bytes >= 1024 && i < ${#units[@]} - 1 )); do
		bytes=$(( bytes / 1024 ))
		((i++))
	done

	echo "${bytes}${units[$i]}"
}

escape()
{
	case "$1" in
		clear) printf "\e[2J";;
		cursor_enable_blinking) printf "\e[2q";;
		cursor_disable_blinking) printf "\e[0q";;
		save_term) printf "\e[?1049h";;
		restore_term) printf "\e[?1049l";;
		save_cursor) printf "\e7";;
		restore_cursor) printf "\e8";;
		move_cursor_up) printf "\e[%sA" "${2:-1}";;
		move_cursor_down) printf "\e[%sB" "${2:-1}";;
		set_cursor) printf "\e[%s;%sH" "${2:-1}" "${3:-1}";; # row, col
		hide_cursor) printf "\e[?25l";;
		show_cursor) printf "\e[?25h";;
		reset) printf "\e[0m";;
		erase_line_to_cursor) printf "\e[1K";;
		erase_cursor_to_end) printf "\e[0K";;
		invert_color) printf "\e[7m";;
		reinvert_color) printf "\e[27m";;
		black_color) printf "\e[30m";;
		red_color) printf "\e[31m";;
		green_color) printf "\e[32m";;
		yellow_color) printf "\e[33m";;
		blue_color) printf "\e[34m";;
		magenta_color) printf "\e[35m";;
		cyan_color) printf "\e[36m";;
		white_color) printf "\e[37m";;
		default_color) printf "\e[39m";;
		black_bg_color) printf "\e[40m";;
		red_bg_color) printf "\e[41m";;
		green_bg_color) printf "\e[42m";;
		yellow_bg_color) printf "\e[43m";;
		blue_bg_color) printf "\e[44m";;
		magenta_bg_color) printf "\e[45m";;
		cyan_bg_color) printf "\e[46m";;
		white_bg_color) printf "\e[47m";;
		default_bg_color) printf "\e[49m";;
		dim) printf "\e[2m";;
		undim) printf "\e[22m";;
	esac
}


justify_to_term_width()
{
	local left=$1
	local right=$2

	local left_no_escape right_no_escape
	left_no_escape=$(sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' <<< "$left")
	right_no_escape=$(sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' <<< "$right")

	local len=$((COLS - ${#left_no_escape} - ${#right_no_escape}))
		spaces=$(printf "%${len}s" "")
		printf "%s" "$left$spaces$right"
	}

render_bottom()
{
	local file_info spaces selected dir_info index

	escape set_cursor "$((ROWS - 1))" 0
	if (( ${#CURRENT_DIR_CONTENT[@]} )); then
		selected=${CURRENT_DIR_CONTENT[SELECTED]}

		file_info="$(stat -c "%A %G " "$selected")"
		file_info="$file_info$(format_bytes "$(stat -c "%s" "$selected")") "
		file_info="$file_info$(date -d "$(stat -c "%z" "$selected")" +'%Y-%m-%d %H:%M') $(escape reset)"
		index="($((SELECTED + 1))/${#CURRENT_DIR_CONTENT[@]})"
		else
			file_info="$(escape reset)"
			index="(0/0)"
	fi

	dir_info="$(escape blue_color)$(escape invert_color)$index"

	justify_to_term_width "$dir_info" "$file_info"
}

render_top()
{
	escape set_cursor
	local selected dims
	selected="$(escape blue_color)$CURRENT_DIR$(escape white_color)${CURRENT_DIR_CONTENT[SELECTED]}"
	dims="$ROWS x $COLS"

	justify_to_term_width "$(escape green_color)$(whoami)@$(uname -n)$(escape white_color) $selected" "$SEARCH_QUERY" #"$dims"
}

render_input() 
{
	case "$MODE" in
		command)
			escape show_cursor
			escape cursor_enable_blinking
			escape set_cursor "$ROWS"
			clean="${CURRENT_INPUT//$'\n'/}"
			clean="${clean:0:$((COLS-1))}"
			printf ":%-$((COLS-1))s" "$clean"
			escape set_cursor "$ROWS" $((${#CURRENT_INPUT} + 2))
			;;
		search)
			escape show_cursor
			escape cursor_enable_blinking
			escape set_cursor "$ROWS"
			clean="${CURRENT_INPUT//$'\n'/}"
			clean="${clean:0:$((COLS-1))}"
			printf "/%-$((COLS-1))s" "$clean"
			escape set_cursor "$ROWS" $((${#CURRENT_INPUT} + 2))
			;;
		*)
			escape set_cursor "$ROWS"
			clean="${CURRENT_MESSAGE//$'\n'/}"
			clean="${clean:0:$((COLS-1))}"
			printf "%-$((COLS-1))s" "$clean"
			;;
	esac
}

clear_file_list()
{
	for (( i=2; i < $((ROWS-1)); i++ )); do
		escape set_cursor $i $((COLS/2))
		escape erase_line_to_cursor
	done
}

get_filetype_color()
{
	local file=$1
	if [[	-d "$file" ]]; then
		escape blue_color
	elif [[	-L "$file" ]]; then
		escape cyan_color
	elif [[	-f "$file" ]]; then
		escape default_color
		if [[ -x "$file" ]]; then
			escape green_color
		fi
	elif [[	-b "$file" ]]; then
		escape yellow_color
	elif [[	-c "$file" ]]; then
		escape magenta_color
	else
		escape white_color
	fi
}

render_file_list_entry()
{
	local id=$1
	local pos=$((id-FILE_LIST_OFFSET+2))
	is_file_visible "$id"
	local visible=$?
	if [[ "$visible" = "1" ]]; then
		escape set_cursor $pos
		if (( id == SELECTED )); then
			escape invert_color
		fi
		local element=${CURRENT_DIR_CONTENT[$id]}
		local global_element="$CURRENT_DIR$element"
		get_filetype_color "$global_element"
		printf "%-$((COLS/2 - 1))s" " $element"
		escape reset
	fi
}

render_entire_file_list()
{
	local iter=0
	for element in "${CURRENT_DIR_CONTENT[@]}"; do
		render_file_list_entry $iter
		((iter+=1))
	done
}

render_selected_content()
{
	local mid=$(((COLS/2)+1))
	local i=2
	local maxlen=$((COLS - mid - 1))

	for j in $(seq 2 $((ROWS-2))); do
		escape set_cursor "$j" "$mid"
		escape erase_cursor_to_end
	done

	while IFS= read -r line; do
		escape set_cursor $i "$mid"
		line="${line//$'\t'/    }"
		printf "%s" "${line:0:maxlen}"
		((i++))
	done <<< "$SELECTED_CONTENT"
}

render_grep_result()
{
	local mid=$(((COLS/2)+1))
	local i=2
	local maxlen=$((COLS - mid - 1))

	for j in $(seq 2 $((ROWS-2))); do
		escape set_cursor "$j" "$mid"
		escape erase_cursor_to_end
	done
	
	while IFS= read -r line; do
		escape set_cursor $i "$mid"
		line="${line//$'\t'/    }"
		printf "%s" "${line:0:maxlen}"
		((i++))
		[[ "$i" -ge $((ROWS-2)) ]] && break
	done <<< "$GREP_RESULT"
}

render_right_panel()
{
	case "$RIGHT_PANEL_MODE" in
		preview) render_selected_content;;
		grep) render_grep_result;;
	esac
}

# Fetches the current terminal size, rerenders everything
# and resets navigation variables
redraw()
{
	get_term_size

	escape clear
	get_current_dir_content
	SELECTED=0
	FILE_LIST_OFFSET=0
	render_entire_file_list
	render_top
	render_bottom
	render_command
	update_selected_content
	render_right_panel
}
